config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope "(:locale)", locale: /en|fr|zh-CN/ do
    root 'pages#index'
    get :presentation, to: 'pages#presentation'
    get :membres, to: 'pages#membres'
    # get :comite, to: 'pages#comite'
    get :presse, to: 'pages#presse'
    get :grandes_fortunes, to: 'pages#grandes_fortunes'
    get :livredor, to: 'pages#livredor'
    get :contact, to: 'pages#contact'
    get :concurrents, to: 'pages#competitors'
    post :send_mail, to: 'pages#send_mail'
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/competitor.rb
class Competitor < ActiveRecord::Base
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
end

app/models/member.rb
class Member < ActiveRecord::Base
  mount_uploader :picture, FileUploader
end

app/models/presentation_photo.rb
class PresentationPhoto < ActiveRecord::Base
end

app/models/press_article.rb
class PressArticle < ActiveRecord::Base
  mount_uploader :file, FileUploader
end

app/models/press_link.rb
class PressLink < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  before_save do
    self.author_en = author_fr if author_en.blank?
    self.last_name_en = last_name_fr if last_name_en.blank?
    self.author_cn = author_fr if author_cn.blank?
    self.author_statut_en = author_statut_fr if author_statut_en.blank?
    self.author_statut_cn = author_statut_fr if author_statut_cn.blank?
  end

  def inverse_author_name_fr
    last_name_fr ? last_name_fr : author_fr.split.reverse.join(" ")
  end
  def inverse_author_name_en
    last_name_en ? last_name_en : author_en.split.reverse.join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

private
  def set_locale
    @locale = params[:locale]
    I18n.locale = @locale || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end

  def set_admin_locale
    I18n.locale = :fr
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'application'
  require 'aws-sdk'
  def index

  end

  def presentation
    @source_path = Rails.root.join('app', 'assets', 'images', 'presentation')
    # Because you're never going to commit credentials to source. Please.
    if Rails.env.production?
      Aws.config.update({
          :access_key_id => ENV['S3_KEY'],
          :secret_access_key => ENV['S3_SECRET'],
      })
    else
      creds = JSON.load(File.read('secrets.json'))
      Aws.config.update({
          :access_key_id => creds['AccessKeyId'],
          :secret_access_key => creds['SecretAccessKey'],
      })
    end
    bucket_name = 'cbc-assets'
    s3 = Aws::S3::Client.new(region:'eu-central-1')
    resp = s3.list_objects(bucket: 'cbc-assets', prefix: 'assets/')
    @images = []
    # resp.contents.each_with_index do |object, index|
    #   @images << object.key unless index == 0
    #   # puts "#{object.key} => #{object.value}"
    # end
    @images = resp.contents.map(&:key)
    @images.delete_at(0)
  end

  def membres
    @members = Member.all.order(name: :asc)
  end

  def livredor
    @quotes = Quote.all.sort_by(&:inverse_author_name_fr)
  end

  def comite

  end

  def grandes_fortunes
    @fortunes = Fortune.all.order(global_ranking: :asc)
  end

  def presse
    @source_path = Rails.root.join('app', 'assets', 'images', 'presse')
    @articles = PressArticle.all
    @links = PressLink.all
  end

  def contact

  end

  def competitors
    @competitors = Competitor.all.order(name_fr: :asc)
  end

  def send_mail
    @content = params
    ContactMailer.contact_email(@content).deliver_now
    redirect_to contact_path, notice: 'Merci, votre message a bien été envoyé.'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def boldify_competitors(string, lang)
    string_tab = string.split
    first_word = string_tab.first
    if string.index("Facebook et Viber")
      facebook = "Facebook et Viber"
    elsif string.index("Facebook and Viber")
      facebook = "Facebook and Viber"
    elsif string.index("Facebook 和Viber竞争者")
      facebook = "Facebook 和Viber竞争者"
    end
    if string_tab.index("Kuaidi")
      second_word = "Kuaidi"
    elsif string_tab.index("Weibo")
      second_word = "Weibo"
    elsif string_tab.index("Tudou")
      second_word = "Tudou"
    end

    # if lang == :'zh-CN'
    #   last_word = string_tab.last(2).first
    #   remaining = (string_tab[1..-3] + " " + string_tab.last).join(" ")
    # else
      last_word = string_tab.last
      if second_word
        remaining = string_tab[2..-2].join(" ")
      else
        remaining = string_tab[1..-2].join(" ")
      end
      if facebook
        last_word = string_tab.last(3).join(" ")
        if second_word
          remaining = string_tab[2..-4].join(" ")
        else
          remaining = string_tab[1..-4].join(" ")
        end
      end
    # end
    OpenStruct.new(first_word: first_word, last_word: last_word, remaining: remaining, facebook: facebook, second_word: second_word)
  end
end

app/views/layouts/_footer.html.haml
%footer
  %p{style: 'text-align:center;font-size:18px;'} Chinese Business Club
  %p{style: 'text-align:center;font-weight:bold;'}=link_to("Harold PARISOT", "https://fr.linkedin.com/in/haroldparisot", target: '_blank').html_safe
  %p{style: 'text-align:center;'} 23, rue Balzac, 75008 Paris, FRANCE.
  .images
    =link_to image_tag('WeChat', width: 50, height: 50, style:'margin-left: auto;margin-right: auto;display: inline;'), 'assets/WeChat_qrcode', target: '_blank', style: 'margin-left:auto;margin-right:auto;'
    =link_to image_tag('google_logo', width: 100, height: 75, style:'margin-left: auto;margin-right: auto;display: inline;'), 'https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=chinese%20business%20club', target: '_blank', style: 'margin-left:auto;margin-right:auto;'
    =link_to image_tag('FB', width: 50, height: 50, style:'margin-left: auto;margin-right: auto;display: inline;'), 'https://www.facebook.com/ChineseBusinessClubFranceChine', target: '_blank', style: 'margin-left:auto;margin-right:auto;'
    =link_to image_tag('in', width: 60, height: 54, style:'margin-left: 15px;margin-right: auto;display: inline;'), 'https://www.linkedin.com/in/haroldparisot', target: '_blank', style: 'margin-left:auto;margin-right:auto;'
    =link_to image_tag('tw', width: 60, height: 54, style:'margin-left: auto;margin-right: auto;display: inline;'), 'https://twitter.com/haroldparisot', target: '_blank', style: 'margin-left:auto;margin-right:auto;'
  %p{style: 'text-align:center;'} Copyright © 2016 Chinese Business Club

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Chinese Business Club
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %link{href: 'https://fonts.googleapis.com/css?family=Kaushan+Script', rel: 'stylesheet', type: 'text/css'}
    = csrf_meta_tags
    = analytics_init if GoogleAnalytics.valid_tracker?
  %body
    %header
      = link_to (image_tag 'logo_transparent.png', alt: "Comité France Chine"), root_path, class: 'logo'

      %nav
        %ul.menu_main
          %li=link_to t('home'), root_path
          %li=link_to t('presentation'), presentation_path
          -# %li=link_to t('steering_committee'), comite_path
          %li=link_to t('members'), membres_path
          %li=link_to t('press'), presse_path
          %li=link_to t('livre_dor'), livredor_path
          %li=link_to t('ranking'), grandes_fortunes_path
          %li=link_to t('competitors'), concurrents_path
          %li=link_to t('contact'), contact_path
          %li{style:'margin-right:0px;'}= link_to image_tag('fr.png', size: '20x20'), params.merge(locale: "fr")
          %li{style:'margin-right:0px;'}= link_to image_tag('en.png', size: '20x20'), root_path(locale: :en)
          %li{style:'margin-right:0px;'}= link_to image_tag('cn.png', size: '20x20'), root_path(locale: :'zh-CN')
    .content
      = yield
      = render('layouts/footer')

app/views/pages/comite.html.haml
=image_tag 'membres', class: 'home-cover'
.infos
  %h1=t('steering_committee')
  .text.comite
    .container
      .row
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Rachid Bakhtaoui, Président Esprit de Paris
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Henri Giscard d'Estaing, Président du Club Med
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Pierre Gattaz, Président du Medef
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Laurent Dassault, Groupe Dassault
      .row
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Jean-Paul Agon, PDG de L'Oréal
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Hsueh Sheng Wang, PDG d'Eurasia
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Mingpo Cai, PDG Cathay Capital
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Qide Yu, DG ICBC Bank
      .row
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Zhai Jun, Ambassadeur de Chine en France
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Jufen YAN, Président CCPIT
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Shengliang YANG, DG China UnionPay
        .col-md-3
          = image_tag('membres/logo-aequam')
          %p Xilin WU, Ministre Conseiller

app/views/pages/competitors.html.haml
-# .image-container
%br
%br
%br
%br
%br
%br
%br
%br
=image_tag 'home-cover-2', class: 'home-cover'

.infos.home
  .row.golden_book_fortunes
    .col-md-8.col-md-offset-2
      %h2.h2ranking=t('competitors')
      %br
      - @competitors.each do |competitor|
        - if I18n.locale == :fr
          - if competitor.name_fr.present?
            - stuff = boldify_competitors(competitor.name_fr, I18n.locale)
            %p
              %span{style: 'font-weight:bold;'}=stuff.first_word
              - if stuff.second_word
                %span{style: 'font-weight:bold;'}=stuff.second_word
              %span<= stuff.remaining
              - if competitor.competitor_fr
                %span<= stuff.last_word
              - else
                %span{style: 'font-weight:bold;'}= stuff.last_word
              %span{style: 'font-weight:bold;'}= competitor.competitor_fr
        - elsif I18n.locale == :en
          - if competitor.name_en.present?
            - stuff = boldify_competitors(competitor.name_en, I18n.locale)
            %p
              %span{style: 'font-weight:bold;'}=stuff.first_word
              - if stuff.second_word
                %span{style: 'font-weight:bold;'}=stuff.second_word
              %span= stuff.remaining
              %span{style: 'font-weight:bold;'}= stuff.last_word
        - elsif I18n.locale == :'zh-CN'
          - if competitor.name_cn.present?
            - stuff = boldify_competitors(competitor.name_cn, I18n.locale)
            %p
              %span{style: 'font-weight:bold;'}=stuff.first_word
              - if stuff.second_word
                %span{style: 'font-weight:bold;'}=stuff.second_word
              %span= stuff.remaining
              %span{style: 'font-weight:bold;'}= stuff.last_word

        %br

  %br
  %br
  %br
  %br

app/views/pages/contact.html.haml
-# .image-container
%br
%br
%br
%br
%br
%br
%br
%br
=image_tag 'home-cover-2', class: 'home-cover'

.infos.home
  .row
    .col-md-8.col-md-offset-2
      %h2=t('contact_us')
      - if flash[:notice]
        #notice.alert.alert-success= flash[:notice]
      = form_tag(send_mail_path) do
        = label_tag t('last_name')
        = text_field_tag 'last_name', nil, class: 'form-control', required: true
        = label_tag t('first_name')
        = text_field_tag 'first_name', nil, class: 'form-control', required: true
        = label_tag t('email')
        = email_field_tag 'email', nil, class: 'form-control', required: true
        = label_tag t('subject')
        = text_field_tag 'subject', nil, class: 'form-control', required: true
        = label_tag t('phone')
        = text_field_tag 'phone', nil, class: 'form-control'
        = label_tag t('function')
        = text_field_tag 'function', nil, class: 'form-control'
        = label_tag t('company')
        = text_field_tag 'company', nil, class: 'form-control'
        = label_tag t('message')
        = text_area_tag 'message', nil, rows: 8, class: 'form-control', required: true
        %br
        = submit_tag t('submit'), class: 'btn btn-cbc pull-right'

app/views/pages/grandes_fortunes.html.haml
-# .image-container
%br
%br
%br
%br
%br
%br
%br
%br
=image_tag 'home-cover-2', class: 'home-cover'

.infos.home
  .row.golden_book_fortunes
    .col-md-8.col-md-offset-2
      %h2.h2ranking=t('ranking_title')
      %br
      - @fortunes.each_with_index do |fortune, i|
        - if I18n.locale == :'zh-CN'
          %p.author="#{i + 1}/ #{fortune.first_name_cn}"
        - else
          %p.author="#{i + 1}/ #{fortune.first_name}"
        - if I18n.locale == :fr
          = simple_format(fortune.description_fr, style: 'margin-bottom: 0px;')
          = "Age : #{fortune.age}"
          %br
          = "Fortune : #{fortune.money_fr}"
          %br
          = "Classement mondial: #{fortune.global_ranking}ème position"
          %br
        - elsif I18n.locale == :en
          = simple_format(fortune.description_en, style: 'margin-bottom: 0px;')
          %br
          = "Age : #{fortune.age}"
          %br
          = "Net Worth : #{fortune.money_en}"
          %br
          = "World Ranking: #{fortune.global_ranking}th position"
          %br
        - elsif I18n.locale == :'zh-CN'
          = simple_format(fortune.description_cn, style: 'margin-bottom: 0px;')
          = "年龄 : #{fortune.age}  岁"
          %br
          = "净资产 : #{fortune.money_cn}"
          %br
          = "世界排名 : 第#{fortune.global_ranking}位"
          %br
        %br

  %br
  %br
  %br
  %br

app/views/pages/index.html.haml
-# .image-container
%br
%br
%br
%br
%br
%br
%br
%br
=image_tag 'home-cover-2', class: 'home-cover'

.infos.home
  .row
    .col-md-8.col-md-offset-2
      %h2=t('cbc')
      %p{style: 'text-align:justify;'}=t('develop_network')
      %br
      %a.btn.btn-lg.btn-cbc{style: 'margin-right:auto;margin-left:auto;display:block;width:initial;width:200px;', href: contact_path}=t('contact_us')

app/views/pages/livredor.html.haml
-# .image-container
%br
%br
%br
%br
%br
%br
%br
%br
=image_tag 'home-cover-2', class: 'home-cover'

.infos.home
  .row.golden_book
    .col-md-8.col-md-offset-2
      %h2=t('livre_dor')

      - @quotes.each do |quote|
        - if I18n.locale == :fr
          %p= quote.text_fr
          %p.author<
            = quote.author_fr
            %span>= " #{quote.last_name_fr}"
            = "," if quote.author_statut_fr.present?
            %span>= " #{quote.author_statut_fr if quote.author_statut_fr.present?}"
          %br
        - elsif I18n.locale == :en
          %p= quote.text_en
          %p.author<
            = quote.author_en
            %span>= " #{quote.last_name_en}"
            = "," if quote.author_statut_en.present?
            %span>= " #{quote.author_statut_en if quote.author_statut_en.present?}"
          %br
        - elsif I18n.locale == :'zh-CN'
          %p= quote.text_cn
          %p.author= "#{quote.author_cn}, #{quote.author_statut_cn}"
          %br

      -# %p=t('nicolas_sarkozy')
      -# %br
      -# %br
      -# %p=t('mingpo_cai')
      -# %br
      -# %br
      -# %p=t('laurent_dassaut')
      -# %br
      -# %br
      -# %p=t('renaud_donnedieu_de_vabres')
      -# %br
      -# %br
      -# %p=t('roland_dumas')
      -# %br
      -# %br
      -# %p=t('louis_gallois')
      -# %br
      -# %br
      -# %p=t('robert_hossen')
      -# %br
      -# %br
      -# %p=t('jean_david_levitte')
      -# %br
      -# %br
      -# %p=t('li_li')
      -# %br
      -# %br
      -# %p=t('emmanuel_macron')
      -# %br
      -# %br
      -# %p=t('thierry_mariani')
      -# %br
      -# %br
      -# %p=t('frederic_mitterand')
      -# %br
      -# %br
      -# %p=t('jean_pierre_raffarin')
      -# %br
      -# %br
      -# %p=t('kai_song')
      -# %br
      -# %br
      -# %p=t('hsueh_sheng_wang')
      -# %br
      -# %br
      -# %p=t('qide_yu')
      -# %br
      -# %br
      -# %p=t('jian-fang_zhou')
  %br
  %br
  %br
  %br

app/views/pages/membres.html.haml
=image_tag 'membres', class: 'home-cover'
.infos
  %h1=t('official_members')
  .text.membres
    .container
      .row
        - @members.each do |member|
          .col-md-3
            = link_to image_tag(member.picture), member.url, target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-aequam'), 'http://www.aequamcapital.com/accueil/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-aiguemarine'), 'http://www.aiguemarine-paris.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-amazingfrance'), 'http://www.amazingfrance.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-azoya-group'), 'http://www.azoyagroup.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-bouygues'), 'http://www.bouygues.com/en/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-bucherer'), 'http://www.bucherer.com/en/home.html', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-business-france'), 'http://www.businessfrance.fr/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-azoya-haituncun'), 'http://www.haituncun.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-ccifc'), 'http://www.ccifc.org/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-china-rendez-vous'), 'http://chinarendezvous.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-cyclopharma'), 'http://www.cyclopharma.fr/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-dassault-aviation'), 'http://www.dassault-aviation.com/en/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-efg'), 'http://wp.efgconsultingworldwide.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-euronex'), 'https://www.euronext.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-glevent'), 'http://www.gl-events.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-harold'), 'http://www.haroldparisotconseils.cn/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-intercontinental'), 'http://www.ihg.com/intercontinental/hotels/gb/en/paris/parhb/hoteldetail?cm_mmc=GoogleMaps-_-ic-_-FREN-_-parhb', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-kedge'), 'http://www.kedgebs.com/fr', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-lameco-china'), 'http://www.lamecogroup.com/en/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-laurent-perrier'), 'http://www.laurent-perrier.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-value-retail'), 'http://www.lavalleevillage.com/zh-cn/home/home', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-bristol'), 'http://www.lebristolparis.com/fr/bienvenue/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-meurice'), 'http://www.dorchestercollection.com/paris/le-meurice-hotel', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-royal-monceau'), 'http://www.leroyalmonceau.com/?lang=fr', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-minaledesign'), 'http://www.minaledesignstrategy.com/fr', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-orpea'), 'http://www.orpea.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-parisandco'), 'http://www.parisandco.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-shanghai-traveler-club'), 'http://issuu.com/chinaelitefocus/stacks/a19a258976db4278a3252836af3c6f37', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-shangri'), 'http://www.shangri-la.com/fr/paris/shangrila/dining/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-simon-associes'), 'http://www.simonassocies.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-peninsula'), 'http://paris.peninsula.com/fr/default', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-tcl-alcatel'), 'http://www.tclcom.com/', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-total'), 'http://total.com/en', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-toys-club'), 'http://www.toysclub.fr/en', target: '_blank'
        -# .col-md-3
        -#   = link_to image_tag('membres/logo-yves-rocher'), 'http://www.yves-rocher.cn/', target: '_blank'

app/views/pages/presentation.html.haml
=image_tag 'presentation', class: 'presentation-cover', alt: "Comité France Chine"
.infos
  %h1=t('who_we_are')
  .text.presentation
    .row
      .col-md-3.col-md-offset-1
        .owl-carousel
          -# - (1..77).to_a.shuffle.each do |x|
          -#   = image_tag x.to_s
          -# - Dir.glob("#{@source_path}/*.jpg").each do |press_image|
          - @images.each do |press_image|
            = image_tag('http://cbc-assets.s3.amazonaws.com/' + press_image)
      .col-md-6
        %p.harold=t('about_cbc', link: link_to("Harold PARISOT", "https://fr.linkedin.com/in/haroldparisot", target: '_blank')).html_safe

app/views/pages/presse.html.haml
.infos{style:'margin-top:0px !important;'}
  .text
    %br
    %br
    %br
    %br
    %br
    %br
    %br
    %br
    %br
    %br
    %h1=t('press_articles')
    %br
    #gallery
      - @articles.each do |press_article|
        = link_to image_tag(press_article.file), press_article.file.url, rel: 'example1'
    %br
    %br
    %br
    %h1=t('links')
    %ul
      %iframe{:style => "margin-right:auto; margin-left: auto;display:block;", :allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/5rCXGSId0_Y", :width => "560"}
      %br
      - @links.each do |press_link|
        %li=link_to press_link.title, press_link.url, target: '_blank'